site_name: d-gitea
site_url: https://pages.charlesreid1.com/d-gitea
repo_name: d-gitea
repo_url: https://git.charlesreid1.com/docker/d-gitea
edit_uri: ""

copyright: 'Copyright &copy; 2018 <a href="https://charlesreid1.com">Charles Reid</a>'

docs_dir: docs
site_dir: site
extra_css:
  - css/custom.css
theme: 
  name: null
  custom_dir: 'mkdocs-material/material'
  palette:
    primary: 'light green'
    accent: 'light green'
  logo:
    icon: 'input'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
pages:
  - 'Home':         'index.md'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
